### ISSUE TITLE
Make sure no runtime errors if we have more than one `$(` in the WDL command

### ISSUE THREAD

**Issue by kinow** [common-workflow-lab/wdl-cwl-translator#130]
While reviewing the code today, part of #126 , I noted this line: https://github.com/common-workflow-lab/wdl-cwl-translator/blob/main/wdl2cwl/main_oop.py#L578

It doesn't handle if you have more than `$(` in the string. Looking at the spec, it doesn't say anything about how many `$(` we can have in a WDL command string. But this workflow has multiple: https://github.com/broadinstitute/viral-pipelines/blob/fa070138543df3b6353a17e1821419eb5bd6e87c/pipes/WDL/tasks/tasks_nextstrain.wdl#L486-L499

**Comment by mr-c** [comment]
FYI: There is no `$(` in WDL (that is a BASH/shell construct). There is, however `${` and `~{`

https://github.com/openwdl/wdl/blob/main/versions/1.1/SPEC.md#expression-placeholders-and-string-interpolation

True, all uses of `$(` in a WDL `command` section need escaping before being put a the CWL `InitialWorkDirRequirement` file contents section, so that they do not look like a CWL expression.

**Comment by kinow** [comment]
Thanks @mr-c ! Closed IDE and ran out of :coffee: power for the day. Will try to understand what's being replaced there, and whether the issue can happen or not (was going to use the label "bug?" because I didn't have time to confirm this bug).

**Comment by mr-c** [comment]
The issue can totally happen, if there are two `$(` bash command substitutions in the same line of a WDL `command`, yes!

Good catch.
